try:
    print(x)
except:
    print("an error occured")
finally:
    print("finally")